[project]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "GPT2 from scratch"
name = "gpt-2"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[feature.cuda.system-requirements]
cuda="12.4"

[environments]
default=["cuda"]
local=[]

[tasks]

[dependencies]
python = ">=3.12.7,<4"
jupyterlab = ">=4.2.5,<5"
transformers = ">=4.45.2,<5"
datasets = ">=3.0.1,<4"
tqdm = ">=4.66.5,<5"
ipywidgets = ">=8.1.5,<9"
pytorch = ">=2.4.1,<3"
huggingface_hub = ">=0.25.2,<0.26"
polars = ">=1.9.0,<2"
pytest = ">=8.3.3,<9"

[target.linux-64.pypi-dependencies]
triton = ">=3.0.0, <4"
